### ISSUE TITLE
Duplicated comment

### ISSUE THREAD

**Issue by robertoclavijob** [kaleidos-ventures/taiga-feedback#3]
Steps to reproduce
1.Check-in code using TG number in the commit message
2. Comment in the task using code style
![comment](https://cloud.githubusercontent.com/assets/8324592/20564729/e7f2a054-b164-11e6-9d98-2720886ab22d.png)

Expected result
Only one comment should be published

Actual result
The same comment is published 2 times
![duplicatedcomment](https://cloud.githubusercontent.com/assets/8324592/20564756/0e227678-b165-11e6-9eb6-97f1668c8378.png)

**Comment by superalex** [comment]
Hello @robertoclavijob we are trying to reproduce the issue but we can't, according to our web server your browser did two different PATCH requests to the task API one at 15:04:07 and another at 15:04:08. Is it possible you sent the same comment twice?, did you try adding one more comment to check if it's duplicated too?.

Regards,

**Comment by robertoclavijob** [comment]
No, I sent it only one time, to send it 2 times I should copy and paste and I think I cannot do it in 1 second
I didn't try to send another comment yesterday.

**Comment by superalex** [comment]
Ok, please, let us know if it happens again.

Regards,

**Comment by robertoclavijob** [comment]
ok
